//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Beer", Namespace="http://tempuri.org/")]
    public partial class Beer : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private double AlcPercentageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double AlcPercentage
        {
            get
            {
                return this.AlcPercentageField;
            }
            set
            {
                this.AlcPercentageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BeerServiceReference.BeerServiceSoap")]
    public interface BeerServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name GetBeersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeers", ReplyAction="*")]
        BeerServiceReference.GetBeersResponse GetBeers(BeerServiceReference.GetBeersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeers", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServiceReference.GetBeersResponse> GetBeersAsync(BeerServiceReference.GetBeersRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByName", ReplyAction="*")]
        BeerServiceReference.GetByNameResponse GetByName(BeerServiceReference.GetByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByName", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServiceReference.GetByNameResponse> GetByNameAsync(BeerServiceReference.GetByNameRequest request);
        
        // CODEGEN: Generating message contract since element name query from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeerXmlByQuery", ReplyAction="*")]
        BeerServiceReference.GetBeerXmlByQueryResponse GetBeerXmlByQuery(BeerServiceReference.GetBeerXmlByQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeerXmlByQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServiceReference.GetBeerXmlByQueryResponse> GetBeerXmlByQueryAsync(BeerServiceReference.GetBeerXmlByQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeers", Namespace="http://tempuri.org/", Order=0)]
        public BeerServiceReference.GetBeersRequestBody Body;
        
        public GetBeersRequest()
        {
        }
        
        public GetBeersRequest(BeerServiceReference.GetBeersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBeersRequestBody
    {
        
        public GetBeersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeersResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServiceReference.GetBeersResponseBody Body;
        
        public GetBeersResponse()
        {
        }
        
        public GetBeersResponse(BeerServiceReference.GetBeersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BeerServiceReference.Beer[] GetBeersResult;
        
        public GetBeersResponseBody()
        {
        }
        
        public GetBeersResponseBody(BeerServiceReference.Beer[] GetBeersResult)
        {
            this.GetBeersResult = GetBeersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByName", Namespace="http://tempuri.org/", Order=0)]
        public BeerServiceReference.GetByNameRequestBody Body;
        
        public GetByNameRequest()
        {
        }
        
        public GetByNameRequest(BeerServiceReference.GetByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetByNameRequestBody()
        {
        }
        
        public GetByNameRequestBody(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServiceReference.GetByNameResponseBody Body;
        
        public GetByNameResponse()
        {
        }
        
        public GetByNameResponse(BeerServiceReference.GetByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BeerServiceReference.Beer[] GetByNameResult;
        
        public GetByNameResponseBody()
        {
        }
        
        public GetByNameResponseBody(BeerServiceReference.Beer[] GetByNameResult)
        {
            this.GetByNameResult = GetByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeerXmlByQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeerXmlByQuery", Namespace="http://tempuri.org/", Order=0)]
        public BeerServiceReference.GetBeerXmlByQueryRequestBody Body;
        
        public GetBeerXmlByQueryRequest()
        {
        }
        
        public GetBeerXmlByQueryRequest(BeerServiceReference.GetBeerXmlByQueryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeerXmlByQueryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetBeerXmlByQueryRequestBody()
        {
        }
        
        public GetBeerXmlByQueryRequestBody(string query)
        {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeerXmlByQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeerXmlByQueryResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServiceReference.GetBeerXmlByQueryResponseBody Body;
        
        public GetBeerXmlByQueryResponse()
        {
        }
        
        public GetBeerXmlByQueryResponse(BeerServiceReference.GetBeerXmlByQueryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeerXmlByQueryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBeerXmlByQueryResult;
        
        public GetBeerXmlByQueryResponseBody()
        {
        }
        
        public GetBeerXmlByQueryResponseBody(string GetBeerXmlByQueryResult)
        {
            this.GetBeerXmlByQueryResult = GetBeerXmlByQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface BeerServiceSoapChannel : BeerServiceReference.BeerServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class BeerServiceSoapClient : System.ServiceModel.ClientBase<BeerServiceReference.BeerServiceSoap>, BeerServiceReference.BeerServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BeerServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BeerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), BeerServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BeerServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BeerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BeerServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BeerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BeerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServiceReference.GetBeersResponse BeerServiceReference.BeerServiceSoap.GetBeers(BeerServiceReference.GetBeersRequest request)
        {
            return base.Channel.GetBeers(request);
        }
        
        public BeerServiceReference.Beer[] GetBeers()
        {
            BeerServiceReference.GetBeersRequest inValue = new BeerServiceReference.GetBeersRequest();
            inValue.Body = new BeerServiceReference.GetBeersRequestBody();
            BeerServiceReference.GetBeersResponse retVal = ((BeerServiceReference.BeerServiceSoap)(this)).GetBeers(inValue);
            return retVal.Body.GetBeersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServiceReference.GetBeersResponse> BeerServiceReference.BeerServiceSoap.GetBeersAsync(BeerServiceReference.GetBeersRequest request)
        {
            return base.Channel.GetBeersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServiceReference.GetBeersResponse> GetBeersAsync()
        {
            BeerServiceReference.GetBeersRequest inValue = new BeerServiceReference.GetBeersRequest();
            inValue.Body = new BeerServiceReference.GetBeersRequestBody();
            return ((BeerServiceReference.BeerServiceSoap)(this)).GetBeersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServiceReference.GetByNameResponse BeerServiceReference.BeerServiceSoap.GetByName(BeerServiceReference.GetByNameRequest request)
        {
            return base.Channel.GetByName(request);
        }
        
        public BeerServiceReference.Beer[] GetByName(string name)
        {
            BeerServiceReference.GetByNameRequest inValue = new BeerServiceReference.GetByNameRequest();
            inValue.Body = new BeerServiceReference.GetByNameRequestBody();
            inValue.Body.name = name;
            BeerServiceReference.GetByNameResponse retVal = ((BeerServiceReference.BeerServiceSoap)(this)).GetByName(inValue);
            return retVal.Body.GetByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServiceReference.GetByNameResponse> BeerServiceReference.BeerServiceSoap.GetByNameAsync(BeerServiceReference.GetByNameRequest request)
        {
            return base.Channel.GetByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServiceReference.GetByNameResponse> GetByNameAsync(string name)
        {
            BeerServiceReference.GetByNameRequest inValue = new BeerServiceReference.GetByNameRequest();
            inValue.Body = new BeerServiceReference.GetByNameRequestBody();
            inValue.Body.name = name;
            return ((BeerServiceReference.BeerServiceSoap)(this)).GetByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServiceReference.GetBeerXmlByQueryResponse BeerServiceReference.BeerServiceSoap.GetBeerXmlByQuery(BeerServiceReference.GetBeerXmlByQueryRequest request)
        {
            return base.Channel.GetBeerXmlByQuery(request);
        }
        
        public string GetBeerXmlByQuery(string query)
        {
            BeerServiceReference.GetBeerXmlByQueryRequest inValue = new BeerServiceReference.GetBeerXmlByQueryRequest();
            inValue.Body = new BeerServiceReference.GetBeerXmlByQueryRequestBody();
            inValue.Body.query = query;
            BeerServiceReference.GetBeerXmlByQueryResponse retVal = ((BeerServiceReference.BeerServiceSoap)(this)).GetBeerXmlByQuery(inValue);
            return retVal.Body.GetBeerXmlByQueryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServiceReference.GetBeerXmlByQueryResponse> BeerServiceReference.BeerServiceSoap.GetBeerXmlByQueryAsync(BeerServiceReference.GetBeerXmlByQueryRequest request)
        {
            return base.Channel.GetBeerXmlByQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServiceReference.GetBeerXmlByQueryResponse> GetBeerXmlByQueryAsync(string query)
        {
            BeerServiceReference.GetBeerXmlByQueryRequest inValue = new BeerServiceReference.GetBeerXmlByQueryRequest();
            inValue.Body = new BeerServiceReference.GetBeerXmlByQueryRequestBody();
            inValue.Body.query = query;
            return ((BeerServiceReference.BeerServiceSoap)(this)).GetBeerXmlByQueryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BeerServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BeerServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BeerServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53021/BeerService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BeerServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53021/BeerService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BeerServiceSoap,
            
            BeerServiceSoap12,
        }
    }
}
